name = "JSONSchemaGenerator"
uuid = "b10a6b5e-eaef-4b72-b159-8e5005e98e8e"
authors = ["matthijscox <matthijs.cox@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"

[targets]
test = ["Test", "JSON3", "JSONSchema"]
